### ISSUE TITLE
merging: set lock on index while merging

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/zoekt#319]
Shard merging doesn't set a lock on the index dir which potentially leads to duplicate repositories in compound shards.
The reason why we didn't set a lock so far is that it takes around 3 min to merge a single 2GB compound shard and we
don't want to block other processes like indexing for that long.

However, we have seen duplicate shards in production and the merge process is the most likely culprit.

Proposal
- Update shard merging to create only one compound shard per call
- Set a lock on index dir, similar to how cleanup does it
- Remove duplicate shards

Ideally we would not lock the entire dir while merging, but only set a lock on the involved shards. However we don't 
have a central oracle (yet) that could manage this, but maybe there are other ways to achieve this?

**Comment by keegancsmith** [comment]
cleanup needs a coarse lock since it makes global decisions. But if I am not mistaken cleanup runs relatively quickly, the slow part is asking for the metadata from each shard? If it is slow, we could look into alternative ways to speed it up.

But otherwise it seems like we could be locking by repo id. If you hold a lock by repo id, then the "global" lock can't be held. however, I can imagine us running into deadlock situations. If a job wants to lock A and B, and another wants to lock B and A we can get into deadlock. This trickiness means we need to really think about and design the process such that we avoid deadlocks. 

Alternatively we stick to coarse locks, but never hold them for a long time. This might be possible to achieve since we could do more best effort work and then only lock when we mutate the FS.
