### ISSUE TITLE
Update Bootstrap & jQuery in web/templates.go?

### ISSUE THREAD

**Issue by TobiX** [sourcegraph/zoekt#444]
Not an expert in JavaScript, but the jQuery & Bootstrap dependencies in [web/templates.go](https://github.com/sourcegraph/zoekt/blob/main/web/templates.go) seem pretty old... Would be nice if they were updated to current versions.

**Comment by keegancsmith** [comment]
Everything seems to be working though, if it ain't broke no need to fix. Using the latest major release likely would require some porting. Happy to accept a patch (that has been tested) to update to the latest 3.x version, or maybe even if you test it the latest 5.x version. For now I am closing this since nothing is actually broken. Can re-open if you are interested in updating.
