### ISSUE TITLE
Move zoekt into monorepo

### ISSUE THREAD

**Issue by SuperAuguste** [sourcegraph/zoekt#595]
There aren't all that many people using Zoekt outside of Sourcegraph so we could perhaps consider moving this into the monorepo to simplify the scip-ctags build process.

Currently we need to:
- merge a scip-ctags PR
- merge a PR here
- merge a Zoekt version change PR

and it's quite the hassle; it'd be nice if we could just do it all in one through the monorepo. :)

**Comment by tjdevries** [comment]
To add to this, there are several improvements that I'd like to pursue, but will remain difficult if they're in separate repos:

1. I think we should consider being able to communicate w/ scip between zoekt & soucegraph. We current serialize a lot of extra information we don't need when using the ctags protocol (and all in JSON) and I think this could be improved a lot
2. We're looking to continue to improve and enrich the symbols experience, so we expect to have a lot of changes for symbols/scip-ctags in the future. We want to ensure that both the indexed symbols and the zoekt search symbols stay in sync
3. It's super easy to forget to sync one of the three above (or have some `go.work` style file mess them up).
4. I think we can have some build improvements from having them all in the same repo.

I'll send this to slack and we can chat about it more there if we want.

**Comment by DylanGriffith** [comment]
Hi. GitLab team member here. I'd love to put in a vote for keeping Zoekt as a separate repo. We have made a large investment in rebuilding our code search engine on top of Zoekt (see https://gitlab.com/groups/gitlab-org/-/epics/9404). We've contributed to Zoekt already and plan to keep contributing to Zoekt in the future. We made this investment based on reading https://about.sourcegraph.com/blog/sourcegraph-accepting-zoekt-maintainership and the promises like:

> We will continue to make contributions that make sense for Zoekt's user base and will never eliminate the ability to run Zoekt as a standalone code search engine

I realise you're not suggesting it wouldn't be open source anymore but moving it into a large monorepo of tools that are not applicable to our integration would seriously harm our ability to contribute.

FWIW as a maintainer of another large open source monolithic project (GitLab) I can certainly appreciate the maintenance burden of having dependencies outside the project that need to be updated and version bumped and so-on. I can definitely see the temptation here but I would love to see it remain independent of the larger sourcegraph project.

**Comment by keegancsmith** [comment]
Thank you for bringing up this discussion. Always good to revisit past assumptions that if different would make our life easier.

> There aren't all that many people using Zoekt outside of Sourcegraph.

There are a fair number. I don't think this would be us acting as a good open source citizen. We should consider other alternatives first before seriously considering this move.

> moving this into the monorepo to simplify the scip-ctags build process.

Realistically how often are you needing to ship a new scip-ctags in Zoekt? For how long will this be the case?

> Currently we need to:
> 
> * merge a scip-ctags PR
> * merge a PR here
> * merge a Zoekt version change PR
> 
> and it's quite the hassle; it'd be nice if we could just do it all in one through the monorepo. :)

Some ideas to reduce toil here. Can we make scip-ctags a universal interface that Zoekt interacts with? IE zoekt only interacts with a scip-ctags binary, and it manages everything else (ie maybe shelling out to universal-ctags). Then the only change needs to be telling Zoekt to use a new version.

Then to solve the Zoekt using a new version issue, the Sourcegraphs monorepo CI republishes the docker images. It could add in the latest version of scip-ctags according to our monorepo.

The manual step for Zoekt deployment on dotcom is a separate discussion. We intentionally do this since we rarely update and want a human to intentionally decide to rolls this out and monitor it.

> To add to this, there are several improvements that I'd like to pursue, but will remain difficult if they're in separate repos:
> 
> 1. I think we should consider being able to communicate w/ scip between zoekt & soucegraph. We current serialize a lot of extra information we don't need when using the ctags protocol (and all in JSON) and I think this could be improved a lot
> 2. We're looking to continue to improve and enrich the symbols experience, so we expect to have a lot of changes for symbols/scip-ctags in the future. We want to ensure that both the indexed symbols and the zoekt search symbols stay in sync
> 3. It's super easy to forget to sync one of the three above (or have some `go.work` style file mess them up).
> 4. I think we can have some build improvements from having them all in the same repo.

I think my suggestion above solves this without merging in Zoekt into the monorepo.

---

Some final extra thought. I don't imagine much of the changes you are making are actually affecting zoekt directly. It seems like its mostly related to the symbol data zoekt consumes and the toil around deps is frustrating. I believe we should tackle that frustration first.

And finally zoekt-webserver command is quite minimal and uses the rest of zoekt as an API. zoekt-sourcegraph-indexserver should really be living inside our monorepo. So an alternative process to consider is keeping zoekt as is, but using artifacts built in our monorepo. There are some downsides to this approach, but I'm happy to discuss this idea further.

**Comment by DylanGriffith** [comment]
> zoekt-sourcegraph-indexserver should really be living inside our monorepo

FWIW GitLab is also building our own indexer separate to this project as well https://gitlab.com/gitlab-org/gitlab-zoekt-indexer . It ultimately ended up being too specific (consuming our internal git APIs) to be applicable for this Zoekt project. But I like that the webserver is super minimal and then everything that backs the index structure and query language is in this repo and can be consumed as a library. It's actually a really important thing for the open source community as this is basically the only viable open source code search specific database that is mature.

**Comment by gianluca-sabena** [comment]
The main repo just changed the licence from apache 2.0 to enterprise/commercial <https://github.com/sourcegraph/sourcegraph/issues/53528>. I personally suggest to keep zoekt in this separate repo at least until this project will remain open source under apache licence.

**Comment by SuperAuguste** [comment]
I agree with all the points listed here and will close this issue - in the end this code being separate didn't actually block me all that much now that all of our build stuff is in the monorepo :)
