### ISSUE TITLE
Not properly indexing Pascal directives

### ISSUE THREAD

**Issue by Alligator-1** [sourcegraph/zoekt#739]
For example:
program.pas:
```
{$IFDEF ABCDEFGH}
writeln('HelloWorld');
{$ENDIF}
```
ABCDEFGH - not indexed!

**Comment by keegancsmith** [comment]
@Alligator-1 can you provide more context on what you are doing? Exactly the commands and searches you are running would be useful.

**Comment by Alligator-1** [comment]
Ok
I deployed zoekt locally on my computer for a quick source search, but at some point I couldn't search by keyword...
Tried searching using a normal file content search - and found what I needed - the files and the location in them that contain my query

Also, I know that gitlab under the hood uses zoekt too, so I'll show you an example from gitlab of what I'm looking for. Locally at my place, I searched using the same sources, having downloaded and indexed them beforehand....


Here's a simple example:
A file containing the line I'm interested in:
[https://gitlab.com/freepascal.org/fpc/source/-/blob/main/compiler/pgenutil.pas?ref_type=heads#L2763](https://gitlab.com/freepascal.org/fpc/source/-/blob/main/compiler/pgenutil.pas?ref_type=heads#L2763)
And an example of a query that found nothing:
[https://gitlab.com/search?search=SKIP_INTERNAL20231102&nav_source=navbar&group_id=12463123&search_code=true&repository_ref=main](https://gitlab.com/search?search=SKIP_INTERNAL20231102&nav_source=navbar&group_id=12463123&search_code=true&repository_ref=main)

Even though it's a gitlab interface, it uses zoekt under the hood as far as I know.... and besides, locally I have zoekt and its behavior is not different - it doesn't find this line in sources either: `SKIP_INTERNAL20231102`

Maybe I'm somehow setting the search string wrong, if you tell me how to do it right I'd appreciate it, thanks!

**Comment by DylanGriffith** [comment]
@Alligator-1 I may be able to help a little from the GitLab side here. I can tell you the project you linked is not using Zoekt for search. We're still rolling out Zoekt at the moment and you can track that work in https://gitlab.com/groups/gitlab-org/-/epics/9404 . Your searches are going to Elasticsearch.

Additionally from my side I can see that your search term is indeed matching but the link you shared is a "Project" search which is looking for projects and not Code. You'll need to click on the "Code" tab on the left hand side to see the matching code.  Also note while you may only see a single match in the Code tab that is because we only show 1 match per file for Elasticsearch which you can read about at https://gitlab.com/gitlab-org/gitlab/-/issues/668 . That is improved in our new Zoekt-powered search which is still being rolled out.

> I deployed zoekt locally on my computer for a quick source search, but at some point I couldn't search by keyword

This I'm not really sure about. My assumption is that this should also match in Zoekt if you set it up and indexed the project correctly. You might want to clarify what you mean by "couldn't search by keyword".

Did any searches work for the indexed project? Was it just this specific string you are searching for that failed? Could you share some screenshots to show what you are searching for.

**Comment by Alligator-1** [comment]
Hmmm, really, I must have been doing something wrong.

I repeated the re-indexing and search on this single file and everything was found.

Repeated full re-indexing - everything became OK!
Thanks, it's my mistake 😟, sorry for the time!
Thanks for the project - very fast search and indexing!

can be closed
