### ISSUE TITLE
Is there a way to allocate more RAM to the Zoekt web server or method for improving search responses?

### ISSUE THREAD

**Issue by bonohubby** [sourcegraph/zoekt#840]
Thank you for developing Zoekt.

I am trying to apply Zoekt to large repositories, and sometimes the search responses are slow.

I guess that if zoekt-webserver uses more RAM to handle shards, the search speed could be improved. Could you let me know if there are any options related to this?
Or, are there methods that can deal with such cases?

Thank you very much!

**Comment by keegancsmith** [comment]
Can you give more details to the environment you are running in and the parameters you are using to index? Additionally example queries that run slow. If indeed RAM is the issue, make sure you are deployed on linux and are giving zoekt enough file caches. IE don't just look at the RAM zoekt has allocated, it heavily relies on mmap + the operating system file cache.

**Comment by bonohubby** [comment]
Dear @keegancsmith, thank you for your response.

I am using the `zoekt-index -parallelism 32 -index /data /repo` or `zoekt-git-index` commands to create shards and running Zoekt with the `zoekt-webserver -rpc -index /data` command.

The default web server that runs is used for testing purposes, and I am using REST API or RPC for code search.

What I am curious about is that when the target size for zoekt-index or zoekt-git-index is large, the size of the generated shards also becomes large, which can lead to slower search speeds. I am wondering if there are any settings or configurations to improve the search response speed on a server with sufficient resources.

Thank you.

**Comment by keegancsmith** [comment]
Can you give details on the number of shards generated for your repo? Zoekt should be creating a shard per 100mb of content and then concurrently searching them. IE to zoekt a large monorepo looks just like a bunch of smaller repos.<br><br>You can try tuning GOMAXPROCS to increase CPU parallelism. But at some point you are going to be IO bound. The reason I ask about operating system/etc is that we use MMAP on linux. Because the fundemental limit is IO, that is why having ample memory for use in the filesystem caches is important.

This is really hard to help with you only giving very light details in github comments. What is useful is to actually see graphs of how your instance is behaving with respect to CPU, memory and IO and finding out where the bottleneck is.

**Comment by bonohubby** [comment]
Thank you very much for your help.
As you mentioned, I will monitor where the bottleneck occurs.
